export default function Head() {
  return (
    <>
      <title>Eg-Formati</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
    </>
  );
}