import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Background } from "@/components/background";
import { Toaster } from "@/components/ui/sonner";
import { Providers } from "./Provider";

const inter = Inter();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      > 
        <Background />
       
        <Providers>
          {children}
        </Providers>
        
        <Toaster />
        
      
      
      </body>
      
    </html>
  );
}
