import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Background } from "@/components/background";
import { Toaster } from "@/components/ui/sonner";
import { Providers } from "./Provider";
import CookieConsent from "@/components/Cookies/cookie-consent";

const inter = Inter();

export const metadata: Metadata = {
  title: "Eg-Formation",
  description: "Generated by create next app",
  icons: '/favicon.svg', // Assure-toi que ton favicon est dans le dossier "public"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <head>
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
        </head>
      <body
        className={`${inter.className} antialiased`}
      > 
        <Background />
       
        <Providers>
          {children}
          <CookieConsent />
        </Providers>
        
        <Toaster />
        
      
      
      </body>
      
    </html>
  );
}
